server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db

app:
  message: Hello, I'm Order Service.

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
