spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

# springdoc:
#   swagger-ui:
#     server-url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  message: Hello, I'm Product Service!

management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh
